name: My NodeJs Email Sender Pipeline

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: "teogisis"
        password: "Atsaoleole123-"
    - name: Build and push Docker image
      run: |
        docker build -t teogisis/emailsender:latest .
        docker push teogisis/emailsender:latest